version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: travelcon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # backend:
  #   build: 
  #     context: .
  #     dockerfile: packages/backend/Dockerfile
  #   environment:
  #     DATABASE_URL: postgresql://postgres:postgres@db:5432/travelcon
  #     NODE_ENV: development
  #     PORT: 3000
  #   depends_on:
  #     - db
  #   ports:
  #     - "3000:3000"

volumes:
  postgres_data: